version: '3.8'

services:
  web:
    build: .
    image: web
    container_name: web
    ports:
      - 5000:5000
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  beat:
    build: .
    command: celery --app project.server.tasks.celery beat --schedule=project/tmp/celerybeat-schedule --loglevel=INFO --pidfile=project/tmp/celerybeat.pid
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  worker:
    build: .
    command: celery --app project.server.tasks.celery worker --loglevel=INFO --concurrency=10 -n __CELERY__@%h
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  celery-queue-get_all_sheets:
    build: .
    command: celery --app project.server.tasks.celery worker -Q get_all_sheets --hostname=SMARTSHEET_SHEETS@%h
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
  
  # celery-queue-add:
  #   build: .
  #   command: celery --app project.server.tasks.celery worker -Q add --hostname=TEST_ADD_REGISTERS_END_TO_END@%h
  #   volumes:
  #     - .:/usr/src/app
  #   environment:
  #     - FLASK_DEBUG=1
  #     - APP_SETTINGS=project.server.config.DevelopmentConfig
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - web
  #     - redis
  
  celery-queue-salesforce_test:
    build: .
    command: celery --app project.server.tasks.celery worker -Q test_contact_salesforce --hostname=SALESFORCE_TEST_CONTACT@%h
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      
  celery-queue-get_sheet_syngenta_direct_greenfield:
    build: .
    command: celery --app project.server.tasks.celery worker -Q get_sheet_syngenta_direct_greenfield --hostname=SMARTSHEET_SHEET_SYNGENTA_DIRECT_GREENFIELD@%h
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  flower:
    build: .
    command: celery --app project.server.tasks.celery flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
